# ============================================================
# IngressRoute — Argo CD Dashboard (Traefik)
# ============================================================

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: argocd

spec:
  # ------------------------------------------------------------
  # EntryPoints
  # ------------------------------------------------------------
  entryPoints:
    - websecure

  # ------------------------------------------------------------
  # Routes
  # ------------------------------------------------------------
  routes:
    - match: Host(`argocd.kub.techcats.org`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80

  # ------------------------------------------------------------
  # TLS Configuration
  # ------------------------------------------------------------
  tls:
    secretName: argocd-tls-secret
