# ============================================================
# ConfigMap - CoreDNS (Forward External DNS to Pi-hole)
# ============================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
    app.kubernetes.io/name: coredns

data:
  Corefile: |
    .:53 {
        errors
        health
        ready

        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
        }

        forward . 192.168.10.104       # forward all non-cluster DNS to Pi-hole
        cache 30
        loop
        reload
        loadbalance
    }
