# ============================================================
# PersistentVolume - MariaDB
# ============================================================

apiVersion: v1
kind: PersistentVolume

metadata:
  name: mariadb-pv

spec:
  capacity:
    storage: 4Gi

  accessModes:
    - ReadWriteOnce

  storageClassName: longhorn-retain
  persistentVolumeReclaimPolicy: Retain

  csi:
    driver: driver.longhorn.io
    volumeHandle: mariadb
---

# ============================================================
# PersistentVolumeClaim - MariaDB
# ============================================================

apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: mariadb-pvc
  namespace: mariadb

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: longhorn-retain

  resources:
    requests:
      storage: 4Gi

  volumeName: mariadb-pv
