# ============================================================
# Longhorn StorageClass (Retain Policy)
# ============================================================

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-retain

provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

parameters:
  numberOfReplicas: "3"
  dataEngine: "v1"
