# ============================================================
# IngressRoute — Longhorn Dashboard (Traefik)
# ============================================================

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn-system

spec:
  # ------------------------------------------------------------
  # EntryPoints
  # ------------------------------------------------------------
  entryPoints:
    - websecure

  # ------------------------------------------------------------
  # Routes
  # ------------------------------------------------------------
  routes:
    - match: Host(`longhorn.kub.techcats.org`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80

  # ------------------------------------------------------------
  # TLS Configuration
  # ------------------------------------------------------------
  tls:
    secretName: longhorn-tls-secret
