# ============================================================
# Longhorn ServiceAccount
# ============================================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: longhorn-sa
  namespace: longhorn-system

  labels:
    app.kubernetes.io/managed-by: argocd
