# ============================================================
# Argo CD Application - Velero (Vault CSI + MinIO Integration)
# ============================================================

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: homelab

  # ------------------------------------------------------------
  # Destination Cluster
  # ------------------------------------------------------------
  destination:
    server: https://kubernetes.default.svc
    namespace: velero

  # ------------------------------------------------------------
  # Sources
  # ------------------------------------------------------------
  sources:
    # ----------------------------------------------------------
    # 1. Git Repository (Helm values reference)
    # ----------------------------------------------------------
    - repoURL: git@github.com:whitehatcats/k3s-homelab-gitops.git
      targetRevision: main
      ref: values

    # ----------------------------------------------------------
    # 2. Velero Helm Chart (VMware Tanzu)
    # ----------------------------------------------------------
    - repoURL: https://vmware-tanzu.github.io/helm-charts
      chart: velero
      targetRevision: 11.1.0
      helm:
        valueFiles:
          - $values/infra/velero/values.yaml   # reference to Git-based values

    # ----------------------------------------------------------
    # 3. Local Overlay (SPC, Certificates, Extra Manifests)
    # ----------------------------------------------------------
    - repoURL: git@github.com:whitehatcats/k3s-homelab-gitops.git
      targetRevision: main
      path: infra/velero/resources

  # ------------------------------------------------------------
  # Sync Policy
  # ------------------------------------------------------------
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - Validate=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=true

  # ------------------------------------------------------------
  # Ignore Differences
  # ------------------------------------------------------------
  # Prevent Argo CD from repeatedly reconciling auto-generated CRDs
  # and webhook configurations created by Helm or Velero components.
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
