# ============================================================
# DaemonSet — Kube-VIP (Control Plane Virtual IP)
# ============================================================

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-vip-ds
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube-vip-ds
    app.kubernetes.io/version: v0.8.2

spec:
  # ------------------------------------------------------------
  # Selector
  # ------------------------------------------------------------
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-vip-ds

  # ------------------------------------------------------------
  # Pod Template
  # ------------------------------------------------------------
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kube-vip-ds
        app.kubernetes.io/version: v0.8.2

    spec:
      # ------------------------------------------------------------
      # Node Affinity — Control Plane Nodes Only
      # ------------------------------------------------------------
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists

      # ------------------------------------------------------------
      # Containers
      # ------------------------------------------------------------
      containers:
        - name: kube-vip
          image: ghcr.io/kube-vip/kube-vip:v0.9.1
          imagePullPolicy: Always
          args:
            - manager

          env:
            - name: vip_arp
              value: "true"
            - name: port
              value: "6443"
            - name: vip_interface
              value: "eth0"
            - name: vip_cidr
              value: "32"
            - name: cp_enable
              value: "true"
            - name: cp_namespace
              value: "kube-system"
            - name: vip_ddns
              value: "false"
            - name: svc_enable
              value: "false"
            - name: svc_leasename
              value: plndr-svcs-lock
            - name: vip_leaderelection
              value: "true"
            - name: vip_leasename
              value: plndr-cp-lock
            - name: vip_leaseduration
              value: "5"
            - name: vip_renewdeadline
              value: "3"
            - name: vip_retryperiod
              value: "1"
            - name: address
              value: "192.168.10.250"
            - name: prometheus_server
              value: ":2112"

          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW

      # ------------------------------------------------------------
      # Network and Scheduling
      # ------------------------------------------------------------
      hostNetwork: true
      serviceAccountName: kube-vip
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
