# ============================================================
# Job | Sync Grafana Admin Credentials from Vault
# ============================================================

apiVersion: batch/v1
kind: Job
metadata:
  name: sync-grafana-vault
  namespace: monitoring
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: vault-sync

spec:
  # ------------------------------------------------------------
  # Job Configuration
  # ------------------------------------------------------------
  backoffLimit: 1

  template:
    spec:
      serviceAccountName: sa-grafana        # must have Vault access (roleName = grafana)
      restartPolicy: OnFailure

      # ------------------------------------------------------------
      # Containers
      # ------------------------------------------------------------
      containers:
        - name: sync-grafana-vault
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "🔐 Syncing Grafana admin credentials from Vault..."
              sleep 10
              echo "✅ Sync complete."

          volumeMounts:
            - name: secrets-store
              mountPath: /mnt/secrets-store
              readOnly: true

      # ------------------------------------------------------------
      # Volumes
      # ------------------------------------------------------------
      volumes:
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: vault-grafana-admin
