# ============================================================
# SecretProviderClass - WordPress (Vault Integration)
# ============================================================

apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass

metadata:
  name: vault-wp-secrets
  namespace: wordpress


# ------------------------------------------------------------
# Vault Provider Configuration
# ------------------------------------------------------------
spec:
  provider: vault

  parameters:
    vaultAddress: "https://vault.vault.svc:8200"
    vaultTLSCaCert: "/vault/userconfig/ca/ca.crt"
    vaultMountPath: "kubernetes"
    roleName: wordpress

    objects: |
      # ---- WordPress Site Meta ----
      - objectName: "wordpress-username"
        secretPath: "kv/data/wordpress/site"
        secretKey: "username"

      - objectName: "wordpress-password"
        secretPath: "kv/data/wordpress/site"
        secretKey: "password"

      - objectName: "wordpress-email"
        secretPath: "kv/data/wordpress/site"
        secretKey: "email"

      - objectName: "wordpress-blog-name"
        secretPath: "kv/data/wordpress/site"
        secretKey: "blogName"

      # ---- External MariaDB ----
      - objectName: "mariadb-password"
        secretPath: "kv/data/wordpress/db"
        secretKey: "password"


  # ----------------------------------------------------------
  # Synced Kubernetes Secrets
  # ----------------------------------------------------------
  secretObjects:
    - secretName: vault-wp-admin-secret
      type: Opaque
      data:
        - objectName: "wordpress-username"
          key: wordpress-username
        - objectName: "wordpress-password"
          key: wordpress-password
        - objectName: "wordpress-email"
          key: wordpress-email
        - objectName: "wordpress-blog-name"
          key: wordpress-blog-name

    - secretName: vault-wp-db-secret
      type: Opaque
      data:
        - objectName: "mariadb-password"
          key: mariadb-password
