apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-prod
  sources:
    - repoURL: registry-1.docker.io/bitnamicharts
      chart: wordpress
      targetRevision: 27.1.3
      helm:
        valueFiles:
          - $values/apps/wordpress/base/values.yaml
          - $values/apps/wordpress/overlays/prod/patch-values.yaml
    - repoURL: git@github.com:whitehatcats/k3s-homelab-gitops.git
      targetRevision: main
      ref: values
    - repoURL: git@github.com:whitehatcats/k3s-homelab-gitops.git
      targetRevision: main
      path: apps/wordpress/overlays/prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
