# ============================================================
# Certificate | Vault Internal TLS
# ============================================================

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-internal-tls
  namespace: vault


# ------------------------------------------------------------
# Specification
# ------------------------------------------------------------
spec:
  # ----------------------------------------------------------
  # Secret Configuration
  # ----------------------------------------------------------
  secretName: vault-internal-tls      # Secret created by cert-manager
  commonName: vault.vault.svc         # Primary CN used by Vault pods

  # ----------------------------------------------------------
  # DNS Names (SANs)
  # ----------------------------------------------------------
  dnsNames:
    # Service-level SANs
    - vault.vault.svc
    - vault.vault.svc.cluster.local
    - '*.vault.vault.svc'
    - '*.vault.vault.svc.cluster.local'

    # Per-pod DNS names (required for Raft)
    - vault-0.vault-internal.vault.svc
    - vault-1.vault-internal.vault.svc
    - vault-2.vault-internal.vault.svc
    - vault-0.vault-internal.vault.svc.cluster.local
    - vault-1.vault-internal.vault.svc.cluster.local
    - vault-2.vault-internal.vault.svc.cluster.local

  # ----------------------------------------------------------
  # IP Addresses
  # ----------------------------------------------------------
  # Includes localhost to allow probes and CLI connections to work
  ipAddresses:
    - 127.0.0.1

  # ----------------------------------------------------------
  # Certificate Lifetime
  # ----------------------------------------------------------
  duration: 8760h       # 1 year
  renewBefore: 240h     # Renew 10 days before expiration

  # ----------------------------------------------------------
  # Private Key Configuration
  # ----------------------------------------------------------
  privateKey:
    algorithm: RSA
    size: 2048

  # ----------------------------------------------------------
  # Certificate Usages
  # ----------------------------------------------------------
  usages:
    - digital signature
    - key encipherment
    - server auth

  # ----------------------------------------------------------
  # Issuer Reference
  # ----------------------------------------------------------
  issuerRef:
    name: vault-ca-issuer   # internal CA or ClusterIssuer
    kind: Issuer
