# ============================================================
# Hubble UI IngressRoute (via Traefik)
# ============================================================

apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hubble
  namespace: kube-system

spec:
  # ------------------------------------------------------------
  # EntryPoints
  # ------------------------------------------------------------
  entryPoints:
    - websecure

  # ------------------------------------------------------------
  # Routes
  # ------------------------------------------------------------
  routes:
    - match: Host(`hubble.kub.techcats.org`)
      kind: Rule
      services:
        - name: hubble-ui
          port: 80

  # ------------------------------------------------------------
  # TLS Configuration
  # ------------------------------------------------------------
  tls:
    secretName: hubble-tls-secret
